
version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon S3...
      - aws s3 sync --exact-timestamps --region ap-northeast-1 ./ s3://oca-frontend --exclude ".git*" --exclude ".gitpod.yml" --exclude "README.md" --delete
Footer
