#https://dev.classmethod.jp/articles/deploy-web-site-with-github-actions/
name: S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp --recursive --region ap-northeast-1 ./ s3://oca-frontend --exclude ".git*" --exclude ".gitpod.yml" --exclude "README.md" 
